### ISSUE TITLE
Limit Packets before server response

### ISSUE THREAD

**Issue by martinduke** [ietf-wg-masque/draft-ietf-masque-connect-udp#11]
@DavidSchinazi in #10 suggested I file this as a separate issue.

The anonymization properties of MASQUE make it a nice vector to send out large bursts of datagrams to unsuspecting targets. It would be wise for MASQUE proxies to implement some sort of hard limit on datagrams it's willing to transmit without hearing anything from the server.

Of course, the client here is working harder than either the proxy or the server, but it would be bad to get the proxy IP on a denylist.

**Comment by DavidSchinazi** [comment]
This should be fixed in today's update to the drafts.
