### ISSUE TITLE
The default template is not a very good solution

### ISSUE THREAD

**Issue by bemasc** [ietf-wg-masque/draft-ietf-masque-connect-udp#123]
The default template's purpose is to enable compatibility with origin-only proxy configuration schemes.  This is a worthwhile goal, but the default template is not a suitable solution:
* It violates RFC 8615's definition of .well-known/ as the location for *metadata* about an origin.  A MASQUE service is not metadata.
* It is not representable as a .well-known "URI suffix" as required by the .well-known registry (unless we register all (2^128 + 2^32)*2^16 distinct paths).
* It conflicts with better discovery mechanisms, like the one [proposed earlier](https://datatracker.ietf.org/doc/html/draft-schinazi-masque-protocol-03#section-2) in the MASQUE development process.
* It is not compatible with the use of HTTPS records.  (In the targeted legacy context, the client has no other DNS server that can be used when a proxy is in use.)  This is somewhat ironic, as HTTPS records allow bootstrapping QUIC connections, and proxying for QUIC is the primary motivation for CONNECT-UDP.

We should defer this problem to a subsequent draft, and provide a cohesive proxy setup flow, presumably with a standardized configuration object that could be served from .well-known/ and extended to cover CONNECT-IP, DoH and other relevant capabilities.

**Comment by DavidSchinazi** [comment]
Fundamentally I disagree with your assessment that this solution isn't good and should be removed. This serves a real purpose. Let's go into the issues individually:

> * It violates RFC 8615's definition of .well-known/ as the location for _metadata_ about an origin.  A MASQUE service is not metadata.
> * It is not representable as a .well-known "URI suffix" as required by the .well-known registry (unless we register all (2^128 + 2^32)*2^16 distinct paths).

Those points are not an argument to remove the default template, they are an argument to revert PR #90 and switch back to a non-well-known prefix. Let's set those aside for now.

> * It conflicts with better discovery mechanisms, like the one [proposed earlier](https://datatracker.ietf.org/doc/html/draft-schinazi-masque-protocol-03#section-2) in the MASQUE development process.

I don't see a conflict here: the default template doesn't preclude using other templates that have been discovered through other means. Can you clarify what the conflict is?

> * It is not compatible with the use of HTTPS records.  (In the targeted legacy context, the client has no other DNS server that can be used when a proxy is in use.)  This is somewhat ironic, as HTTPS records allow bootstrapping QUIC connections, and proxying for QUIC is the primary motivation for CONNECT-UDP.

Can you clarify what the incompatibility is here? I don't understand what the relationship between the default template and HTTPS records is. Clients are welcome to query their own HTTPS records before using CONNECT or CONNECT-UDP. The way that the client picks its template has no impact on its DNS settings.

**Comment by bemasc** [comment]
...
> Those points are not an argument to remove the default template, they are an argument to revert PR #90 and switch back to a non-well-known prefix.

This is called "squatting on the HTTP namespace", and it would violate the [guidance](https://datatracker.ietf.org/doc/html/rfc7320#section-2.3) in RFC 7320.  It's also messy to implement, as it would require mixing MASQUE-specific "routing" rules with the user's application-specific routing rules.

> > * It conflicts with better discovery mechanisms, like the one [proposed earlier](https://datatracker.ietf.org/doc/html/draft-schinazi-masque-protocol-03#section-2) in the MASQUE development process.
> 
> I don't see a conflict here: the default template doesn't preclude using other templates that have been discovered through other means. Can you clarify what the conflict is?

It doesn't prevent better discovery mechanisms, but it doesn't encourage them either.  From the server side, there would be no way to "opt out" of the default path, due to the potential for clients that have implemented this specification but not a later, better discovery mechanism.  Servers that would prefer a different path would still have to operate the default path for backwards-compatibility.

> > * It is not compatible with the use of HTTPS records.  (In the targeted legacy context, the client has no other DNS server that can be used when a proxy is in use.)  This is somewhat ironic, as HTTPS records allow bootstrapping QUIC connections, and proxying for QUIC is the primary motivation for CONNECT-UDP.
> 
> Can you clarify what the incompatibility is here? I don't understand what the relationship between the default template and HTTPS records is.

The relationship is that the default template cannot express the existence of a DNS server affiliated with the MASQUE server.

> Clients are welcome to query their own HTTPS records before using CONNECT or CONNECT-UDP.

No, they are not, as this would violate the privacy guarantees implicit in the legacy proxy settings UI that this feature is trying to preserve.

**Comment by DavidSchinazi** [comment]
You're conflating two types of proxies here:
1. traditional enterprise proxies that speak CONNECT today and can be updated to speak CONNECT-UDP
2. privacy proxies designed to protect a user's privacy from the network

Folks won't ever be deploying both of these use cases on the same proxy. Your concerns are valid but they only apply to (2). (2) would never use the default template. The default template only applies to (1).

**Comment by bemasc** [comment]
Client software generally can't tell _why_ a proxy is being used.  It just knows that an HTTP CONNECT proxy has been configured with a particular protocol, domain, and port.  Its behavior has to be correct for any existing use case.

I don't see why privacy proxies wouldn't use the default template.  Privacy proxies that are configured via the existing Secure Web Proxy configuration mechanisms (e.g. browser extensions, system settings) would have no other way to use MASQUE.

Also, I think this distinction is false.  Enterprises are free to use HTTP CONNECT proxies to conceal certain information from the network (e.g. using an employees-only browser extension), and enterprises are often opinionated about which DNS server ought to be used (not controllable via a browser extension).

**Comment by DavidSchinazi** [comment]
Your discovery draft sounds great - however the default template doesn't get in the way of that. I don't think it's reasonable to remove a useful feature because we might have a more complete solution later when the useful feature doesn't get in the way of the future complete solution.
