### ISSUE TITLE
Editorial suggestion: to proxy UDP over HTTP -> to tunnel UDP over HTTP

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-connect-udp#124]
Right in the first sentence in the intro we talk about proxying UDP over HTTP. The term proxy is later defined, however, in this first sentence I find it more confusing then helpful as it is generally not well defined. My proposal would be to you the verb "tunnel" instead at least in the into; this is what is also used for http connect.

**Comment by DavidSchinazi** [comment]
Tunnels are a well-defined HTTP concept, so I'd avoid that word in the first sentence. Can you clarify how this is confusing: in what way can it be misinterpreted?

**Comment by mirjak** [comment]
the term proxy is a bit overloaded and people often assuming some additional functionality than just forwarding, e.g. connection interception. I thought tunnel would be more neutral. But if that would confuse another set of people, it might not be better. Was just a suggestion...

**Comment by DavidSchinazi** [comment]
Thanks, your suggestion definitely made sense but I think that in this case proxy ends up being better than tunnel.
