### ISSUE TITLE
Editorial: Tunnels are commonly used to.... 

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-connect-udp#125]
section 3 (http exchanges) has the following sentence and I don't understand the intention of this sentence:

`Tunnels are commonly used to create an end-to-end virtual connection, 
which can then be secured using [QUIC](https://www.ietf.org/archive/id/draft-ietf-masque-connect-udp-08.html#QUIC) [QUIC] 
or another protocol running over UDP.`

Is the intention of this sentence only to provide a definition of "tunnel"? In this case it should maybe be move into section 1.1? Or is there something else this sentence should tell me and I didn't get?

**Comment by DavidSchinazi** [comment]
[HTTP Semantics](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-semantics-19#section-9.3.6) also uses the term "tunnel" to describe CONNECT.

**Comment by DavidSchinazi** [comment]
Section 3 already describes in detail what it means by a UDP tunnel, can you clarify what's unclear?

**Comment by mirjak** [comment]
The sentence just seems a bit out of context in this paragraph (maybe check the whole paragraph). If the intent is to just define the term tunnel, I think it would be ore useful to move this sentence to section 1.1. If this sentence is trying to tell me more than defining what a UDP tunnel is, then I don't understand the sentence. So what is this sentence supposed to tell me?

**Comment by LPardue** [comment]
The purpose of the text here is to inform implementations what the purpose of the HTTP exchange is (the tunnel is the purpose). That's important for HTTP implementers to understand why they would add support for it. E.g. If a server does not want to support that purpose, then it should reject it.

**Comment by DavidSchinazi** [comment]
I'm not sure I see what's wrong here. Do you have a suggestion?

**Comment by LPardue** [comment]
The single paragraph seems fine to me and in-keeping with the style that other HTTP documents use to speak about similar concepts. The only change I _might_ suggest is to move the sentence "Tunnels are commonly used to create an end-to-end virtual connection, which can then be secured using [QUIC](https://ietf-wg-masque.github.io/draft-ietf-masque-connect-udp/draft-ietf-masque-connect-udp.html#QUIC) [QUIC] or another protocol running over UDP." to immediately after the first sentence of the paragraph.

**Comment by DavidSchinazi** [comment]
Thanks @LPardue, I like that - wrote it up as #129
