### ISSUE TITLE
sec 3.1: "In IPv4, the Don't Fragment (DF) bit MUST be set if possible"

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-connect-udp#126]
"MUST" and "if possible" sounds wacky... maybe "if possible by the provided socket interface" or something...?

**Comment by DavidSchinazi** [comment]
This text was inspired by the [same one in RFC 9000](https://datatracker.ietf.org/doc/html/rfc9000#section-14):
> UDP datagrams MUST NOT be fragmented at the IP layer.  In IPv4, the Don't Fragment (DF) bit MUST be set if possible, to prevent fragmentation on the path.

**Comment by DavidSchinazi** [comment]
I'd rather not go into details of sockets since that won't make the intent clearer to the reader.

**Comment by mirjak** [comment]
Okay. We don't need to talk about sockets. But it still not fully sure what exactly is meant by "if possible"...?

**Comment by mirjak** [comment]
I would go for "if possible by the underlying interface" to make it clear what this exception is about. However, just a suggestion.

**Comment by DavidSchinazi** [comment]
Thanks for the suggestion! I think I'm going to stick with the RFC 9000 text for consistency
