### ISSUE TITLE
Editorial suggestion: First sentence section 5

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-connect-udp#130]
I had to read the first sentence multiple time to parse it:

`When associated with UDP proxying request streams, the HTTP Datagram Payload 
field of HTTP Datagrams (see [HTTP-DGRAM]) has the format defined in [Figure 6].`

I think turning the sentence around would make it slightly easier tor read:

`The HTTP Datagram Payload field of HTTP Datagrams (see [HTTP-DGRAM]) 
has the format defined in [Figure 6], when associated with streams of UDP proxying requests.`

**Comment by DavidSchinazi** [comment]
I think I find it easier to read the other way around

**Comment by LPardue** [comment]
Or split the difference

> When HTTP Datagrams [HTTP-DGRAM] are associated with UDP proxying request streams, the HTTP Datagram Payload field has the format defined in [Figure 6].

**Comment by mirjak** [comment]
that works too. I also found the term "UDP proxying request streams" a bit clumsy. but the new sentence works much better. Thanks!
