### ISSUE TITLE
DoS potential with ICMP recommendation

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-udp#139]
Section 3.1:

'If a proxy is notified by its operating system that its socket is no longer usable (for example, this can happen when an ICMP "Destination Unreachable" message is received, see Section 3.1 of [ICMP6]), it MUSTclose the request stream.'

What is suggested in this sentence makes it possible to do a denial of service on the service the proxy attempts to provide. The attacker needs to know the source and destination IP and port, with that information one can send an spoofed ICMP "Destination Unreachable" to the server for each proxied flow the attack knows about. ICMP validation can help if it is actually providing enough information. However, I would assume that the proxy does not remember its UDP payloads and thus can't verify them and where the rest of the IP/UDP info can be spoofed beyond address and ports.

**Comment by DavidSchinazi** [comment]
This DoS potential is a property of OSes that use BSD sockets, not of CONNECT-UDP. If the sockets isn't usable, there's nothing a CONNECT-UDP application can do. ICMP validation can only be performed by the OS because applications don't see the ICMP payload. I agree that it would better to not have this problem, but there's unfortunately nothing that can be done in this document.

**Comment by gloinul** [comment]
Re-reading in the context of your comment I understand now what you meant. First reading it I maybe latched on that for this context this is a bad idea. However, is this a more general issue, i.e. I as proxy server allocated resources to exchange your UDP packets, I am no longer capable therefore I need to indicate this to the client. The appropriate way of doing that signalling is closing the stream. I think the example might lead the reader in the wrong direction to more specific than the main aspect really is.

**Comment by DavidSchinazi** [comment]
Thanks for following up Magnus. Editorially, I do find the example to be helpful here. Do you happen to have an editorial suggestion here that would help without removing this example?
