### ISSUE TITLE
Misattribution

### ISSUE THREAD

**Issue by mnot** [ietf-wg-masque/draft-ietf-masque-connect-udp#149]
> By virtue of the definition of the Capsule Protocol (see {{HTTP-DGRAM}}), unreliable CONNECT
requests do not carry any message content. Similarly, successful UDP proxying responses also do not
carry any message content.

That's not because of how the Capsule Protocol works -- it's how [CONNECT works](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#CONNECT).

**Comment by DavidSchinazi** [comment]
It is how CONNECT works, though in HTTP/1.1 the Capsule Protocol doesn't use CONNECT - it uses GET and inherits this lack of message content property from the use of Upgrade. I'd be happy to write that up, but I think that relying on the definition of the Capsule Protocol might be editorially simpler?

**Comment by mnot** [comment]
Fair call.
