### ISSUE TITLE
How do you salami slice CONNECT-UDP stream data?

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-udp#15]
So I'd kinda forgotten that when H3 DATAGRAMS are not available (e.g. in HTTP/2 etc) CONNECT-UDP allows a mode where UDP datagram payload is transferred to the proxy as one contiguous bytestream of HTTP payload. How do receiving endpoints slice up this bytestream to ensure the atomic payloads are reconstructed properly? A proxy needs to make sure it sends the correct payload in the UDP datagram is will send, a client needs to construct the accurate UDP datagram payload in order to process whatever protocol it is tunnelling.

The specification doesn't say anything about how message boundaries might be signalled or acted upon. Is the intention maybe to rely on DATA frames for delineation? Implementations might not be able to guarantee that frames boundaries match 1:1. For instance quiche provides a r[ecv_body() method](https://docs.quic.tech/quiche/h3/struct.Connection.html#method.recv_body) to read arbitrary amounts of payload data from request streams; DATA rame boundaries are not exposed to applications.

**Comment by tfpauly** [comment]
It's this, right?
```
If HTTP/3 datagrams are not supported, the stream is used to convey UDP payloads, by prefixing them with a 16-bit length.
```

**Comment by LPardue** [comment]
I think so yes. I missed it somehow, so perhaps some editorial work would help improve things. For instance, the DATAGRAM frame supports up to 62-bit lengths but in this case case the frame is limited to 16 bits.

In the API I mentioned earlier, a proxy would need to try and read 2 bytes from the stream, then try to read as many bytes as the length indicated. That's certainly doable but needs a bit work in the application side. 

In the opposite direction there's a problem if the target presents datagrams larger than 16 bits. We might want to highlight that the proxy can only drop these on the floor. Endpoints should be able to deal with that just like any PTB situation.

**Comment by mirjak** [comment]
I actually thought that would be nice to use DATA frames as this would allow for more extensibility. How hard would it be to expose frame boundary for a masque implementation? Alternatively we could maybe define a new frame type?

**Comment by DavidSchinazi** [comment]
This should be fixed in today's update to the drafts.

**Comment by mirjak** [comment]
I saw that the new draft version proposes "CONNECT-UDP Stream Chunk". This looks like a good approach, however, I would still like to conclude the discussion why this is better than using HTTP DATA frames.

**Comment by LPardue** [comment]
My initial intuition is that Stream Chunks were conveyed in DATA frames. I'm wondering if I lept to the wrong conclusion.

P.S: I also wondered if Stream Chunk should actually be an HTTP/3 frameset of its own. I think some minor editorialization that could help clarify things.

**Comment by DavidSchinazi** [comment]
Yes, Stream Chunks are conveyed over DATA frames. Stream Chunks have their own framing (as opposed to using the DATA frame boundaries) to simplify implementation, and to support HTTP/1.1 where there are no HTTP DATA frames.
