### ISSUE TITLE
Conflicting example and requirement

### ISSUE THREAD

**Issue by mnot** [ietf-wg-masque/draft-ietf-masque-connect-udp#150]
The client configuration section says:

> * All template variables MUST be within the path component of the URI.

... but the examples contain:

~~~
https://proxy.example.org:4443/masque?h={target_host}&p={target_port}
https://proxy.example.org:4443/masque{?target_host,target_port}
~~~

Which is it?

**Comment by DavidSchinazi** [comment]
This was an accident, I suspect it dates back to when the document referred to `:path` which contains both path and query. Fixing to mention both path and query via #162.
