### ISSUE TITLE
*single* Connection field

### ISSUE THREAD

**Issue by mnot** [ietf-wg-masque/draft-ietf-masque-connect-udp#154]
> * the request SHALL include a single "Connection" header field with value
  "Upgrade" (note that this requirement is case-insensitive as per {{Section
  7.6.1 of HTTP}}).

"Single" implies that there can't be other values (at least in other header lines, and possibly this one). That's an inappropriate constraint.

**Comment by DavidSchinazi** [comment]
Thanks for catching this oversight, fixing via #160.
