### ISSUE TITLE
*single* upgrade value

### ISSUE THREAD

**Issue by mnot** [ietf-wg-masque/draft-ietf-masque-connect-udp#155]
> * the request SHALL include a single "Upgrade" header field with value
  "connect-udp".
  
"Single" implies that this mechanism is incompatible with any other upgrade mechanisms. If that's actually the case, it might be good to state so explicitly, rather than rely on this single word.

**Comment by DavidSchinazi** [comment]
Thanks for catching this oversight. Similar to #154, this was not the intent. Fixing via #161.
