### ISSUE TITLE
What purpose does datagram-flow-id fulfill?

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-udp#16]
I think it might help to make the purpose of the datagram-flow-id header clearer in the specification.

For context, I was giving an overview of HTTP/3 CONNECT-UDP to someone completely new to MASQUE. The inclusion of a flow ID in the H3 DATAGRAM frame makes total sense, it's for multiplexing. However, in my example, the client made a request on stream ID 0 and used a datagram-flow-id of 0. Partly because of this overlap, the person I was presenting to made the comment "why do you need the datagram-flow-id header, couldn't you just use the stream ID"? Since the stream and datagram flow IDs have a linked lifetime, this observation makes some sense. 

There might be benefits to having independence between stream ID and flow ID space. However, having reread the spec a few times now, I think the main purpose comes from the intention to be flexible. What I mean by that is, the use of HTTP/3 DATAGRAMS is opportunistic and that it is reasonable to fallback to carying tunnelled UDP datagram payload on streams. So, is the primary intention that "datagram-flow-id" is echoed in responses to allow clients to understand if they can use DATAGRAMS or if they have to use streams?

**Comment by DavidSchinazi** [comment]
The purpose of the Datagram-Flow-Id header is to negotiate which flow ID to use. An alternative could be to use stream IDs, but that has downsides:
- it means that we'll be more likely to use longer encodings for flow IDs
- it needlessly ties the two namespaces (stream ID / flow ID) together, which prevents innovation - for example in [quic-proxy](https://tools.ietf.org/html/draft-pauly-masque-quic-proxy-00) we have multiple requests share a flow ID

**Comment by LPardue** [comment]
Thanks for the clarification. That challenges my earlier statement that alluded to "CONNECT-UDP sharing fate with the flow ID", they actually have more independence. It might be worth saying something about flow ID reuse across requests, I presume that reuse is an error in the case of vanilla CONNECT-UDP but is fine in quic-proxy when requests are used for active flow ID manipulation?

**Comment by mirjak** [comment]
I thought the main reason is that the QUIC stream ID is not exposed to the HTTP layer? However, even if a different stream ID is used on the QUIC layer, you could still use the datagram ID to remember the associated stream on the HTTP layer.

**Comment by DavidSchinazi** [comment]
This should be fixed in today's update to the drafts.

**Comment by mirjak** [comment]
@DavidSchinazi can you say a bit more here how this is addressed. I don't think I saw anything in the new docs that e.g. talk about re-use (or did I miss that?). I guess it would be helpful to say a bit more about how to handle flow ID then just saying there is a service doing it....

**Comment by DavidSchinazi** [comment]
@mirjak yes, I need to add a few more clarifications, that work is tracked by https://github.com/DavidSchinazi/draft-h3-datagram/issues/9
