### ISSUE TITLE
Consider error codes for the client to terminate CONNECT-UDP streams

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-udp#17]
Imagine a client wants to talk HTTP to a server via a proxy.

For basic HTTP/3, the optimal case is to talk QUIC-in-QUIC via MASQUE and DATAGRAMs. But that requires the proxy (or chain of proxies) to support DATAGRAMs. So a client might discover via the CONNECT-UDP response that only the stream mode is available. 

Transferring QUIC over a reliable stream has some problems. A client might decide its not worth the effort and want to just fallback to HTTP over TLS (via just a CONNECT stream). At such a point, it would likely want to abort the stream and having an error code to indicate this could help the MASQUE server understand that this happened.

There's a variant of the above. Since the server can't judge UDP connectivity, it's upon the client to actively close the stream if it detects connectivity issues. An error code to this effect might also help.

**Comment by mirjak** [comment]
Actually I was wondering if there is any reason for the masque proxy to not support datagram mode (as long as datagrams are negotiated in the handshake of the QUIC tunnel connection underneath).

However, not sure if we need to let the proxy know why a client aborts a stream. What should the proxy do with this information?

**Comment by LPardue** [comment]
More specific error codes could allow the proxy to detect a higher rate of client drop outs for a specific reason. That usefulness is debatable (hence this issue :)).

This specific chaining case is allowed by the specification, so we should assume that some deployment might end up using it. Dynamic deployments might find that the proxy chain conditions change in an uncoordinated way, finding why clients are grumpy via metrics is a lot easier than waiting for user reports.

**Comment by DavidSchinazi** [comment]
There hasn't been much interest in this feature, and it will be straightforward to implement it as an extension. I'm closing this issue as out of scope for the base CONNECT-UDP spec. Please comment/reopen if you disagree and we can discuss at IETF 113.
