### ISSUE TITLE
The format of target_host and target_port should be defined more formally

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-connect-udp#180]
The draft currently states `target_host supports using DNS names, IPv6 literals and IPv4 literals.` To avoid confusion, we should make an editorial tweak to specify this more formally.

Probably something along the lines of
```
target_host = IPv6address / IPv4address / reg-name
target_port = port
```
using IPv6address, IPv4address, reg-name, and port from RFC 3986. With the additional requirement that both target_host and target_port MUST NOT be empty.

**Comment by gloinul** [comment]
So ":" are allowed in URI as general delimiters. But, ":" is explicitly allowed in the pchar element that is used by path-abempty that the path segmenet specification that applies for HTTPs scheme per RFC 9110. Thus, I appear that it would in fact be allowed. But, it would be good to check with someone that really knows the HTTPS scheme to understand how general interpreters would deal with the ":".
