### ISSUE TITLE
Rename payload to UDP Proxying Payload

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-connect-udp#181]
When working on draft-schinazi-connect-udp-listen we realized that referring to the `Payload` field in Section 5 of CONNECT-UDP can be confused with the `HTTP Datagram Payload` from HTTP-DGRAM. Let's rename this `Payload` to `UDP Proxying Payload` to prevent miscomprehension.

**Comment by LPardue** [comment]
I appreciate the problem but figure 6 already calls the combined context ID and payload fields the "UDP Proxying HTTP Datagram Payload". So now is the proposal to call the field, in full expansion, "UDP Proxying HTTP Datagram Payload UDP Proxying Payload"? Doesn't really grok well

**Comment by DavidSchinazi** [comment]
Though no one does "full expansion" of these fields right?

**Comment by LPardue** [comment]
If they did, we could avoid having redundant field names ;)

But if we ignore that, and we go with `UDP Proxying Payload` (a fine name) , consider also adding that disambiguator to the `Context ID` field such as `UDP Proxying Context ID`. This would help avoid it being confused with the CONNECT-IP context ID

**Comment by DavidSchinazi** [comment]
Though I'd argue that the CONNECT-UDP Context ID and the CONNECT-IP Context ID are the same field so there's no confusion to be had (:

**Comment by LPardue** [comment]
I dunno, they are defined to be very similar but they are different fields.
