### ISSUE TITLE
We are getting a line-length error for the following text (comment 4)

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-udp#185]
We are getting a line-length error for the following text.
     Please let us know how we may update.

Original (1 character too long):
GET https://example.org/.well-known/masque/udp/192.0.2.6/443/ HTTP/1.1

and

Original (2 characters too long):
https://example.org/.well-known/masque/udp/{target_host}/{target_port}/

**Comment by DavidSchinazi** [comment]
I guess we could save 2 characters by replacing `example.org` with `m.example`

**Comment by DavidSchinazi** [comment]
Though I'll check with the RFC Editor, those errors might be ignorable since this renders fine
