### ISSUE TITLE
Address Capsules are insufficiently specified

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-udp#191]
I realize that we need to remember this text from RFC 9000: 

"Packet and frame diagrams in this document use a custom format. The purpose of this format is to summarize, not define, protocol elements. Prose defines the complete semantics and details of structures."

The issue is with at least the adderss assigned capsule: 

The ADDRESS_ASSIGN capsule contains a sequence of zero or more Assigned Addresses.[¶](file:///Users/eramswd/ietf/draft-ietf-masque-connect-ip/draft-ietf-masque-connect-ip.html#section-4.6.1-3)

Assigned Address {
  Request ID (i),
  IP Version (8),
  IP Address (32..128),
  IP Prefix Length (8),
}
[Figure 4](file:///Users/eramswd/ietf/draft-ietf-masque-connect-ip/draft-ietf-masque-connect-ip.html#figure-4): [Assigned Address Format](file:///Users/eramswd/ietf/draft-ietf-masque-connect-ip/draft-ietf-masque-connect-ip.html#name-assigned-address-format)
Request ID:
If this address assignment is in response to an Address Request (see [Section 4.6.2](file:///Users/eramswd/ietf/draft-ietf-masque-connect-ip/draft-ietf-masque-connect-ip.html#addr_req)), then this field SHALL contain the value of the corresponding field in the request. Otherwise, this field SHALL be zero.[¶](file:///Users/eramswd/ietf/draft-ietf-masque-connect-ip/draft-ietf-masque-connect-ip.html#section-4.6.1-5.2.1)
IP Version:
IP Version of this address assignment. MUST be either 4 or 6.[¶](file:///Users/eramswd/ietf/draft-ietf-masque-connect-ip/draft-ietf-masque-connect-ip.html#section-4.6.1-5.4.1)
IP Address:
Assigned IP address. If the IP Version field has value 4, the IP Address field SHALL have a length of 32 bits. If the IP Version field has value 6, the IP Address field SHALL have a length of 128 bits.[¶](file:///Users/eramswd/ietf/draft-ietf-masque-connect-ip/draft-ietf-masque-connect-ip.html#section-4.6.1-5.6.1)
IP Prefix Length:
The number of bits in the IP Address that are used to define the prefix that is being assigned. This MUST be less than or equal to the length of the IP Address field, in bits. If the prefix length is equal to the length of the IP Address, the receiver of this capsule is only allowed to send packets from a single source address. If the prefix length is less than the length of the IP address, the receiver of this capsule is allowed to send packets from any source address that falls within the prefix.[¶](file:///Users/eramswd/ietf/draft-ietf-masque-connect-ip/draft-ietf-masque-connect-ip.html#section-4.6.1-5.8.1)

So the actual data format is missing for IP version and IP prefix, and only implicit for IP Address. 
I would guess they are both unsinged int, but that is not specified. 
Same corrections needs to be applied to the other capsules.

**Comment by LPardue** [comment]
Wrong repo?

**Comment by gloinul** [comment]
Yes, Intended for Connect-IP
