### ISSUE TITLE
Handling of odd-numbered "datagram-flow-id"  

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-udp#21]
When processing a CONENCT-UDP request a server might apply some checks to decide if the request is valid. First, does the request contain a "datagram-flow-id", second is the value a valid sh-integer, and third is the value a valid client-initiated flow ID (even numbered).

The spec doesn't really talk about that third condition. And there is an interesting interplay with https://tools.ietf.org/html/draft-schinazi-quic-h3-datagram-05, which states requirements on flow ID allocation but clearly highlights that DATAGRAMs can be sent with even or odd flow IDs by either endpoint.

While we continue to use flow ID with CONNECT-UDP, I think it might help to add some text about what a server should do.

**Comment by DavidSchinazi** [comment]
This should be fixed in today's update to the drafts.
