### ISSUE TITLE
Handling of "in-use" flow IDs

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-udp#22]
Slightly related to #21 but image the following scenario that uses syntactically valid flow IDs

First
```
:method: CONNECT-UDP
:path: example.com:443
:authority: example.com:443
datagram-flow-id: 0

status: 200

<datagram exchanges>
```

Second
```
:method: CONNECT-UDP
:path: other.example.com:443
:authority: other.example.com:443
datagram-flow-id: 0

status: ???
```

The second request should probably be rejected with a 4xx error. The spec alludes to that possibility (apart from the weird bit about "governed by":

> Any response other than a successful response indicates that the tunnel has not yet been formed and that the connection remains governed by HTTP.

I think it might help to call this error condition out more explicitly.

**Comment by DavidSchinazi** [comment]
This should be fixed in today's update to the drafts.
