### ISSUE TITLE
CONNECT-UDP Stream Chunk extensibility

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-udp#24]
https://tools.ietf.org/html/draft-ietf-masque-connect-udp-01#section-5 defines Stream Chunk and follows up with a statement about extensibility

```
CONNECT-UDP Stream Chunk {
     CONNECT-UDP Stream Chunk Type (i) = 0x00,
     UDP Payload Length (i),
     UDP Payload (..),
   }

<snip/>

   The bidirectional stream that the CONNECT-UDP request was sent on is
   a sequence of CONNECT-UDP Stream Chunks.  The CONNECT-UDP Stream
   Chunk Type is designed to allow future extensibility.  Endpoints that
   receive a chunk with an unknown CONNECT-UDP Stream Chunk Type MUST
   silently skip over that chunk.
```

It isn't clear to me if the `UDP Payload Length` field belongs solely to type `0x00` or if its expected to be the chunk length and applicable to all Chunk Types that are known or unknown. If the chunk length in *not*common to all chunks, I don't see how an endpoint can silently skip unknown chunks.

**Comment by DavidSchinazi** [comment]
You're absolutely right, that text is not very well written. What I meant to say is that the type and length are generic and the value depends on the type - and if the type is 0x00 then the value is a UDP payload. I'll fix the text.

**Comment by DavidSchinazi** [comment]
I fixed the text in [draft-ietf-masque-connect-udp-02](https://tools.ietf.org/html/draft-ietf-masque-connect-udp-02), closing.
