### ISSUE TITLE
multiplexing flows

### ISSUE THREAD

**Issue by marten-seemann** [ietf-wg-masque/draft-ietf-masque-connect-udp#27]
QUIC allows a client to use a single UDP port to establish connections to an arbitrary number of servers. Packets are demultiplexed to their respective connections by their connection ID.

It would be nice if MASQUE allowed the proxy to do the same thing. To do so, the client could indicate that packets sent on flow M can be multiplexed on the same socket that flow N uses. The proxy would then be allowed to send all UDP packets it receives from the target on flow N.

Is that something this document should specify, or would this better be moved to an extension?

**Comment by DavidSchinazi** [comment]
My personal preference would be to move this to an extension, since it's not required for CONNECT-UDP to work.

**Comment by tfpauly** [comment]
@marten-seemann that sounds like it's in the scope of https://tfpauly.github.io/quic-proxy/draft-pauly-masque-quic-proxy.html

**Comment by DavidSchinazi** [comment]
Based on discussion, it sounds like this will be better served by an extension. So I'm closing this issue with no action. Please reopen/comment if you disagree.
