### ISSUE TITLE
Are stream chunks HTTP/3 frames?

### ISSUE THREAD

**Issue by marten-seemann** [ietf-wg-masque/draft-ietf-masque-connect-udp#28]
The draft is not clear if stream chunks are 
1. HTTP/3 frames (and as such serialized onto the QUIC stream directly), or 
2. if they're supposed to be sent as the payload of HTTP/3 DATA frames.

I assume 1., and I'd be happy to come up with an editorial PR to clarify this.

**Comment by DavidSchinazi** [comment]
Stream chunks are sent as the payload of h3 DATA frames, or the payload of h2 DATA frames, or directly in the TLS stream in HTTP/1.1. I'll clarify the text.

**Comment by marten-seemann** [comment]
> Stream chunks are sent as the payload of h3 DATA frames, or the payload of h2 DATA frames

I'm sure you have a reason for this. Why don't we define a new frame type here? I realize that this means using a different serialization for H2 and H3, but this is something your HTTP stack would most likely know how to handle.

**Comment by DavidSchinazi** [comment]
What's the benefit of defining a new frame? CONNECT uses DATA frames; a departure from that would increase complexity.

**Comment by DavidSchinazi** [comment]
Overcome by events: stream chunks were removed in 649890881aaa92548b5a0fb37a7622b409b281fd. Closing.
