### ISSUE TITLE
Tunneling of ECN Marks

### ISSUE THREAD

**Issue by martinduke** [ietf-wg-masque/draft-ietf-masque-connect-udp#29]
Even if CONNECT-UDP has no explicit ECN support without an extension, there is ambiguity relating to copying of ECN bits between 'inner' and 'outer' datagrams. MASQUE is not strictly IP-in-IP, though it's close to it, so it's not clear if RFC 6040 applies.  Nevertheless, I would propose the following principles:

- ECN markings on the MASQUE connection SHOULD NOT be copied to any resulting UDP datagrams sent by the proxy; they should apply to the MASQUE connection only. If MASQUE congestion control is disabled per section 9, it MUST mark all packets non-ECT.
- ECN markings on incoming UDP datagrams SHOULD NOT be copied to the IP headers of MASQUE packets that encapsulate them: upstream congestion should not affect the congestion state of the MASQUE connection.

I'm happy to write a PR to that effect.

**Comment by DavidSchinazi** [comment]
When using CONNECT-UDP without extensions, the server-facing UDP sockets on the proxy will not be configured to use ECN, so there will not be any ECN markings on the proxy-server path. In other words, ECN will not be in use, so do we need text about it? Adding text to clarify this sounds reasonable, but it probably should be generic to anything in the IP header.

**Comment by martinduke** [comment]
The extensions explicitly concern markings on DATAGRAM frames in the inner connection. The server may very well be sending packets with ECT(0). With no extension, it will eventually stop, but nevertheless these shouldn’t appear in MASQUE IP headers.

**Comment by DavidSchinazi** [comment]
Agreed. I'll take you up on your offer to write a PR then :)

**Comment by gloinul** [comment]
Yes, I think that being clear that for this case the two legs needs to be kept seperate unless internal signalling is used on client to proxy leg to influence the external side setting and receiving of these values.
