### ISSUE TITLE
MASQUE scheme registration needs its own section or possibly document

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-udp#33]
So the URI scheme registration rules (https://datatracker.ietf.org/doc/rfc7595/) have a number of things to consider. Thus, at a minimal the definition needs its own section where that is properly covered. My experience is that the template and definition needs its own sections to make it easy to define clearly and know where things reside. 

I would also note that issue #23 depending on the semantics is for masque scheme and how it relates to the proxied protocol it might make sense to split this scheme out into its own document even if it will be a short one.

**Comment by tfpauly** [comment]
Or, better yet, we don't define any scheme, and just use https for the CONNECT-UDP requests!
