### ISSUE TITLE
Should datagram extension be RECOMMENDED

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-udp#34]
I understand that we can't require datagram support as we need fallback to other HTTP versions. However, can we at least RECOMMEND datagram be implemented?

**Comment by DavidSchinazi** [comment]
I thought that this was clear implicitly, but we could make it explicit - can you send a PR?

**Comment by DavidSchinazi** [comment]
Overcome by events: we now have a dependency on HTTP Datagrams since 649890881aaa92548b5a0fb37a7622b409b281fd. Closing.
