### ISSUE TITLE
No CONNECT-UDP Stream Chunk Types are defined

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-masque/draft-ietf-masque-connect-udp#36]
The draft is not implementable as a result.  Or maybe it is not very useful.  Presumably we need a type defined to carry UDP packets.

**Comment by DavidSchinazi** [comment]
The draft defines 0 for this purpose in [section 6](https://tools.ietf.org/html/draft-ietf-masque-connect-udp-03#section-6). Do you have something else in mind?

**Comment by martinthomson** [comment]
My bad, I completely missed that.  Easy to read past that section.
