### ISSUE TITLE
Encoding of stream chunks on connected streams

### ISSUE THREAD

**Issue by MikeBishop** [ietf-wg-masque/draft-ietf-masque-connect-udp#39]
The text says this about the encoding of stream chunks:

> The bidirectional stream that the CONNECT-UDP request was sent on is a sequence of CONNECT-UDP Stream Chunks....

It's not clearly stated whether HTTP/3 frames stop being used and these stream chunks are written directly into the QUIC stream, or if Stream Chunks are the payload of HTTP/3 DATA frames which are then written into the QUIC stream, or if Stream Chunks are a new HTTP/3 frame type being defined.

CONNECT uses DATA frames, saying this:

> All DATA frames on the stream correspond to data sent or received on the TCP connection. The payload of any DATA frame sent by the client is transmitted by the proxy to the TCP server; data received from the TCP server is packaged into DATA frames by the proxy. Note that the size and number of TCP segments is not guaranteed to map predictably to the size and number of HTTP DATA or QUIC STREAM frames.

Given that support for CONNECT-UDP is not negotiated *a priori*, I think using DATA frames is the only sensible answer in the current state of the text, but the draft doesn't say that clearly.  New HTTP/2 and HTTP/3 frame types for Stream Chunks would also be a viable design that reduces framing overhead, but that's clearly not what the draft currently envisions, since no frame type is registered or defined.

**Comment by DavidSchinazi** [comment]
Yes, the intent of the draft as currently written was to use DATA frames in the same way CONNECT does. We can clarify that.

**Comment by mirjak** [comment]
So what's the trade-offs of using new frames types vs this entirely new stream chunks?

**Comment by MikeBishop** [comment]
Intermediaries, mostly.  Putting chunks in the DATA payload means only the host processing the "request" has to deal with them.  A new frame type means any intermediary needs to understand them at least enough to relay them.  While I find the idea of an intermediary that processes frames but doesn't process HTTP to be questionable, this appeared to be an implicit assumption in several of the discussions yesterday.

If there is no such intermediary, I think a frame type would probably be a cleaner way to spell this, but it's largely a bikeshed.

**Comment by DavidSchinazi** [comment]
Overcome by events: stream chunks were removed in 649890881aaa92548b5a0fb37a7622b409b281fd. Closing.
