### ISSUE TITLE
Echoing "Datagram-Flow-Id" when the request is rejected

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-udp#41]
There can be cases where a proxy detects a request that contains a "Datagram-Flow-Id" is otherwise rejected e.g. missing a mandatory field, contains an odd-numbered ID,  or perhaps the server just decides to return a 5xx. In such cases it is not clear if the proxy should echo the "Datagram-Flow-Id" or not. I don't have a strong preference either way but if its the proxy's choice, we might want to document this so that people don't make assumptions and get surprised.

**Comment by DavidSchinazi** [comment]
I agree, though we probably should mention this in draft-ietf-masque-h3-datagram rather than draft-ietf-masque-connect-udp?

**Comment by LPardue** [comment]
h3-datagram makes no mention of echoing at all. It does mention intermediary stripping though, My first impression is that echoing seems a function of CONNECT-UDP's usage of flow-id. Maybe I'm confused in the overlap?

**Comment by DavidSchinazi** [comment]
Oh, you're right! Maybe we should move echoing from connect-udp to h3-datagram? Do you have thoughts on that?

**Comment by LPardue** [comment]
I probably need to think on it a bit. This seems like one of those difficult to avoid overlaps, so not surprised to see it.

On the one hand, I like that the concept of flow-id is somewhat abstract in h3-datagram. We don't need to get bogged down with some implementation detail that might not apply to a different kind of usage. 

On the other hand, we do spend a whole section defining a header field encoding. So we could refer to the offer/echo pattern as one example way to do things. This might also lend itself nicely to discussing the echo behaviour when named parameters (or whatever we want to call them) are not understood, close to the definition of said parameters. 

I am probably slightly leaning to the second hand here but don't have many cycles to contribute a PR right now.

**Comment by DavidSchinazi** [comment]
Overcome by events: Datagram-Flow-Id was removed in 649890881aaa92548b5a0fb37a7622b409b281fd. Closing.
