### ISSUE TITLE
Move "Stream Encoding of Proxied UDP Packets" to a more appropriate location

### ISSUE THREAD

**Issue by achernya** [ietf-wg-masque/draft-ietf-masque-connect-udp#43]
Currently, the text of the connect-udp draft contains section "Stream Encoding of Proxied UDP Packets", which describes how H3_DATAGRAM can be sent over a reliable stream, e.g., for use with H2 or whenever reliable transmission of datagrams is needed.

One of the current ip-proxying-requirements is that we should be able to optionally transmit datagrams in a reliable fashion.

When we get to writing an implementation of ip-proxying, it would be a bit off to cite the connect-udp draft. One way we could fix this is to move this section to the h3-datagram draft.

**Comment by mirjak** [comment]
I don't want to capture this issue, but I think we should actually reconsider if we really want different CONNECT-UDP and CONNECT_IP methods or just have one CONNECT-X method and provide information on which protocol headers are in the payload or not (and potentially need to be added by the proxy before sending the packet out) in e.g. a HTTP pseudo-headers.

**Comment by DavidSchinazi** [comment]
Overcome by events: that section was removed in 649890881aaa92548b5a0fb37a7622b409b281fd. Closing.
