### ISSUE TITLE
What does it mean for a tunnel to not yet be formed?

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-udp#45]
draft 03 states 

> Any 2xx (Successful) response
   indicates that the proxy has opened a socket to the request-target
   and is willing to proxy UDP payloads.  Any response other than a
   successful response indicates that the tunnel has not yet been
   formed.
   
the use of "not yet" seems a little hand waving. What's the intent of the statement, I think it would help to be more specific. 

We could presume that a non-final 1xx response could indicate that the tunnel is possibly yet to be created. 
Whereas a 4xx could mean that the client erred and that no tunnel is ever going to be created.

**Comment by DavidSchinazi** [comment]
This text was lifted from the [definition of CONNECT](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.6) but I'm sure we can be even more clear. Can you propose some text?

**Comment by LPardue** [comment]
touché

Semantics still says it, so it must mean something https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.9.3.6

But both the H2 and H3 definitions don't really do any handwaving and just say https://tools.ietf.org/html/draft-ietf-quic-http-34#section-4.2

>  A proxy that supports CONNECT establishes a TCP connection
  [RFC0793] to the server identified in the ":authority" pseudo-
   header field.  Once this connection is successfully established, the
   proxy sends a HEADERS frame containing a 2xx series status code to
   the client, as defined in Section 15.3 of [SEMANTICS].

Since CONNECT-UDP is trying to cover all 3 known major versions, it has to be careful. If I **had** to write a PR, I might try to combine the most up to date Semantics text with H2/H3, and in the process drop this "not yet been fully formed" clause. However, maybe I'm missing something that HTTP WG aficionados will tell be is really important.

**Comment by DavidSchinazi** [comment]
So I think it's pretty clear that 2xx means "yes send me your UDP" and 4xx/5xx means "nope don't send your UDP". I think the points that might need clarification are:
1. are 1xx responses allowed?
1. if 1xx is allowed, how does the client react?
1. are 3xx allowed? 
1. if 3xx is allowed, how does the client react?
