### ISSUE TITLE
Stream lifecycle management

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-udp#46]
This is partly related to https://github.com/ietf-wg-masque/draft-ietf-masque-connect-udp/issues/17 but  seems to fit its own issue.

Let's assume a CONNECT-UDP request succeeds with a 2xx and a flow of datagrams is merrily exchanged. How do endpoints indicate they are done with the stream and associated flows? The spec doesn't really say anything. 

The main example I can think of is where a server decides to perform housekeeping on UDP connections (maybe as part of runtime garbage collection, or in reaction to the network stack throwing errors) after a 2xx was been sent. 

H3 CONNECT says

>   The TCP connection can be closed by either peer.  When the client
   ends the request stream (that is, the receive stream at the proxy
   enters the "Data Recvd" state), the proxy will set the FIN bit on its
   connection to the TCP server.  When the proxy receives a packet with
   the FIN bit set, it will close the send stream that it sends to the
   client.  TCP connections that remain half-closed in a single
   direction are not invalid, but are often handled poorly by servers,
   so clients SHOULD NOT close a stream for sending while they still
   expect to receive data from the target of the CONNECT.

 >  A TCP connection error is signaled by abruptly terminating the
   stream.  A proxy treats any error in the TCP connection, which
   includes receiving a TCP segment with the RST bit set, as a stream
   error of type H3_CONNECT_ERROR; see Section 8.  Correspondingly, if a
   proxy detects an error with the stream or the QUIC connection, it
   MUST close the TCP connection.  If the underlying TCP implementation
   permits it, the proxy SHOULD send a TCP segment with the RST bit set.

Not all of that guidance directly translates but I think it would be helpful to set some expectations for endpoints wrt how stream read or write states might change during the lifetime of a CONNECT-UDP request - especially in the cases where no stream data is being exchanged.

**Comment by MikeBishop** [comment]
I took "FIN or RESET = done" as a given, but it's worth stating.  Proxy behavior will likely be identical in both the graceful and abrupt closure cases.
