### ISSUE TITLE
TURN and webtransport

### ISSUE THREAD

**Issue by unicomp21** [ietf-wg-masque/draft-ietf-masque-connect-udp#47]
Thinking from a firewall perspective, and what ports are open now along with which ports will be open in the future, does running TURN over webtransport make sense?  I'm not entirely clear on Masque, what's the difference between TURN and Masque?

**Comment by DavidSchinazi** [comment]
MASQUE is about proxying arbitrary traffic over HTTP, see [the charter](https://datatracker.ietf.org/wg/masque/about/). If you're looking for WebTransport, you're in the wrong place. What are you trying to do?

**Comment by DavidSchinazi** [comment]
Closing as off-topic.

**Comment by unicomp21** [comment]
@DavidSchinazi  I'm trying to get browser based support for tunneling webrtc TURN traffic over http.

**Comment by DavidSchinazi** [comment]
@unicomp21 it does sound like MASQUE, but it's not specific to this git repository. Please join the MASQUE mailing list <https://www.ietf.org/mailman/listinfo/masque> then email <masque@ietf.org> with details of exactly what you're trying to do and why.
