### ISSUE TITLE
Registration capsule from proxy needed?

### ISSUE THREAD

**Issue by ihlar** [ietf-wg-masque/draft-ietf-masque-connect-udp#48]
Section 4 states that the proxy responds to a CONNECT-UDP request with 2xx and a corresponding registration capsule to indicate end-to-end support of datagrams. 
If the client sends a REGISTER_DATAGRAM_CONTEXT capsule, the corresponding capsule from the proxy will be of the same kind, and it will register a new server-generated context ID. So now we would have two context IDs for the same stream, which seems a bit unnecessary. 

Could we simply omit the step where the proxy sends a registration capsule and simply state that a 2xx response to the CONNECT-UDP request is sufficient indication of end-to-end datagram support?

**Comment by LPardue** [comment]
> If the client sends a REGISTER_DATAGRAM_CONTEXT capsule, the corresponding capsule from the proxy will be of the same kind, and it will register a new server-generated context ID.

My reading of the spec is different, https://datatracker.ietf.org/doc/html/draft-ietf-masque-h3-datagram-03#section-4.1 says

> once a  context ID is registered, it can be used in both directions.

So for example, if the client sends a request on stream 4 and then REGISTER_DATAGRAM_CONTEXT { Context ID (0)}, the server will respond with REGISTER_DATAGRAM_CONTEXT { Context ID (0)} to confirm that the context is accepted.

**Comment by ihlar** [comment]
> My reading of the spec is different, https://datatracker.ietf.org/doc/html/draft-ietf-masque-h3-datagram-03#section-4.1 says
> 
> > once a  context ID is registered, it can be used in both directions.
> 
> So for example, if the client sends a request on stream 4 and then REGISTER_DATAGRAM_CONTEXT { Context ID (0)}, the server will respond with REGISTER_DATAGRAM_CONTEXT { Context ID (0)} to confirm that the context is accepted.

That makes sense, I was assuming that the "used in both directions" referred to datagrams. I think my confusion in part came from the same section that says:

> servers MUST NOT register client-initiated Context IDs.

But sending a registration capsule with an already registered context ID is not a new registration I suppose.
Maybe it's good to clarify this a bit in the datagram spec. I'll open a separate issue there.

**Comment by LPardue** [comment]
> Maybe it's good to clarify this a bit in the datagram spec. I'll open a separate issue there.

I agree the draft is a bit ambiguous here.

**Comment by DavidSchinazi** [comment]
Indeed, the spec is unclear here, my apologies. I got this wrong when I rewrote the old Datagram-Flow-Id text. The server doesn't need to echo the registration capsule here since the client's registration is bidirectional.

@LPardue we should add text to HTTP Datagrams to clarify what we want to do about echoing registrations, is it
1. required
2. allowed
3. forbidden

I'm leaning towards (3) unless we have a use case for communicating the fact that a context is "accepted" and in which case I'd say (2).

**Comment by LPardue** [comment]
Aha! In that case I apologise too. This seems important for interop!

Now I remember, I think some people felt registration ack wasn't needed as long as there was a way to reject. And we have that with CLOSE_DATAGRAM_CONTEXT. So I think (3), modelled as implicit accept and explicit close, sounds good. That cuts down the chatter (and probably simplifies some code in my implementation).
