### ISSUE TITLE
Masque TCP with Extended CONNECT:  connect-tcp / masque-tcp

### ISSUE THREAD

**Issue by enygren** [ietf-wg-masque/draft-ietf-masque-connect-udp#55]
With the switch to use Extended CONNECT in #54 for UDP, it seems logical to shift TCP to also use the same model.   Two approaches would either be for a new draft (draft-ietf-masque-connect-tcp?), or to generalize the connect-udp draft since there is lots in-common given how things are now factored.

**Comment by DavidSchinazi** [comment]
I was thinking about that when I wrote the PR and I agree

**Comment by LPardue** [comment]
I'd worry accommodating TCP is scope creep for this draft.

H2 and H3 CONNECT already support TCP. Extended CONNECT might be nicer but then we'd probably want text to explain why endpoints might choose one or another.  That seems better suited to some other document to me right now.

**Comment by DavidSchinazi** [comment]
I'm realizing my "I agree" wasn't very specific, I meant: I agree that we should do the same for TCP. I didn't have a strong opinion for this draft vs a new draft, but based on https://github.com/ietf-wg-masque/draft-ietf-masque-connect-udp/issues/55#issuecomment-918381420 I think a separate draft might be best

**Comment by tfpauly** [comment]
Yeah, this should probably be a separate draft, but defining connect-tcp would be nice to make things more parallel.

**Comment by DavidSchinazi** [comment]
Closing this issue since we'll want to do this in a separate draft
