### ISSUE TITLE
Extended CONNECT bikesheds

### ISSUE THREAD

**Issue by enygren** [ietf-wg-masque/draft-ietf-masque-connect-udp#56]
Some potential bikesheds/comments from #54 (which generally looks good):

1) For HTTP/1.1, should the method be "GET" or "CONNECT"?  WebSockets uses GET -- are there any uses of "Extended CONNECT" that use CONNECT rather than GET?
2) Should the default URI template have a /.well-known prefix?  For example, "/.well-known/masque/udp/{target_host}/{target_port}/" ?
3) Should the upgrade token be "connect-udp" or "masque-udp" ?

**Comment by DavidSchinazi** [comment]
Great questions, but let's keep one issue per topic, I've opened #57, #58, and #59 to track these individual points.
