### ISSUE TITLE
HTTP/1.1 Method for Upgrade

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-connect-udp#57]
For HTTP/1.1, should the method be "GET" or "CONNECT"? WebSockets uses GET -- are there any uses of "Extended CONNECT" that use CONNECT rather than GET?

(issue based on #56 by @enygren)

**Comment by LPardue** [comment]
In my experience, H1.1 CONNECT for anything but it's intended purpose of proxying will see some deployment problems. The last HTTP spec admits some origins might respect it, but I suspect many HTTP components won't like it. I think sticking with GET plus Upgrade header field is a good choice

**Comment by DavidSchinazi** [comment]
At IETF 113, after lengthy discussion the consensus is the room appeared to be to switch to GET so I'm merging #89 so we have a version of the draft ready for WGLC
