### ISSUE TITLE
Well-known prefix for default URI template

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-connect-udp#58]
Should the default URI template have a /.well-known prefix? For example, `/.well-known/masque/udp/{target_host}/{target_port}/` ?

(issue based on #56 by @enygren)

**Comment by DavidSchinazi** [comment]
From the discussion in the room at IETF 113, it appeared folks were OK with `/.well-known/masque/udp/{target_host}/{target_port}/`. I'm going to pick that to close this issue, and we can open another issue during WGLC if we really want to bikeshed this further

**Comment by bemasc** [comment]
It sound like you're writing your own URL parser?  Any reasonable URL library will handle this for you.
