### ISSUE TITLE
MUST NOT Introspect

### ISSUE THREAD

**Issue by ekr** [ietf-wg-masque/draft-ietf-masque-connect-udp#67]
>    Because the CONNECT method creates a TCP connection to the target,
   the target has to indicate its willingness to accept TCP connections
   by responding with a TCP SYN-ACK before the proxy can send it
   application data.  UDP doesn't have this property, so a UDP proxy
   could send more data to an unwilling target than a CONNECT proxy.
   However, in practice denial of service attacks target open TCP ports
   so the TCP SYN-ACK does not offer much protection in real scenarios.
   Proxies MUST NOT introspect the contents of UDP payloads as that
   would lead to ossification of UDP-based protocols by proxies.

This seems like an RFC 6919 "MUST (but we know you won't)"

**Comment by DavidSchinazi** [comment]
Agreed. Are you proposing a change to the draft?

**Comment by ekr** [comment]
Yes. I would remove the last sentence. OTOH, given that the status of proxies is still under discussion maybe we just wait on this one.
