### ISSUE TITLE
Options for avoiding context registration

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-masque/draft-ietf-masque-connect-udp#72]
#71 discusses the fact that many/most extensions to CONNECT-UDP (and likely CONNECT-IP to a lesser degree) don’t need to have dynamic context ID registration via capsules, and that mechanism may be overly complex and burdensome.

I have two options for alternate designs I’d like to propose that should simplify things.

First, some basic assumptions:
- We expect many extensions to be “static” — they will have a defined way to parse what they add to datagram payloads. This includes adding ECN fields, timestamps, or adding ICMP / PING messages.
- We expect some extensions to need more “dynamic” state, specifically for compression of Datagram Payload fields, where we may not know all of the compression contexts at the start of the request.

For both of the options that I’m proposing, I am suggesting that we use the mechanism for nesting extensions that Ben suggested at the last design team meeting — specifically, that an extension defines how to interpret the Datagram payload. If the extension is intended to be composable, it can include a “next payload” VLI at the end which determines the type of the remainder of the payload.

Protocols like CONNECT-UDP and CONNECT-IP would always use the VLI “0” to indicate their default Datagram Payload (UDP payload and IP packet, respectively).

For example, an ECN extension could define itself in one of the following ways:

Not further composable:

```
Datagram {
   Type (i), // VLI indicating that ECN extension is used
   ECN flags (8),
   UDP payload (..)
}
```
Further composable:

```
Datagram {
   Type (i), // VLI indicating that ECN extension is used
   ECN flags (8),
   Next Type (i), // VLI indicating next extension type, 0 if it is UDP payload
   (..)
}
```

Some extension types, or course, don’t make sense to compose, so they wouldn’t define that ability.

I think this kind of composability is preferable to trying to use flag fields and define an order, or trying to negotiated composability rules. It means spending extra VLIs when doing lots of composing, but I expect that to be a limited / minor impact, and one that is worth the simplicity.

The question, then, is what this Type / Context VLI at the start of a datagram is, and how it is allocated. Here are the two options I propose:

### Option 1: Use Capsule Types

The VLI at the start of the datagram is a registered IANA value, which can be the same as the capsule type registry itself. Datagram starts with 0 for the protocol default (UDP body for CONNECT-UDP). For extensions, they use the registered capsule type ID that defines the extension used.

When sending the header that negotiates support for capsules, each side sends an sf-list of sf-integers to indicate the capsule types / extensions they support:

`Capsule-Protocol: 1, 2, 7`

Where in this example, we pretend the following values are defined:

1 = ECN Extension
2 = Timestamp extension
7 = Compression

If your extension needs dynamic mappings, like IP compression, the datagram starts with a fixed value for the capsule that negotiates the extension (7 in this example), and capsules can negotiate a second VLI or something else that actually represents the dynamic mapping.

Pros:
- Doesn’t require capsules to register dynamic types; only extensions that need dynamic state need to use capsules at all.
- Support for extensions is declared in headers, no there is no need to dynamically learning that an extension isn’t supported.
- An implementation receiving a datagram can know exactly what the format of the datagram is, without needing to look up per-request state.

Cons (pretty much all about size efficiency):
- If there are many extension/capsule types, the VLI may go beyond one byte commonly, and thus bloat the datagram.
- Dynamic extensions that create state, like compression, will use two VLIs in the datagram: one for the extension type, and one for the dynamic value. This also can bloat the datagram.

### Option 2: Negotiate values in headers & capsules

The VLI at the start of the datagram is a context ID defined per request stream, but the ID can be allocated via request/response headers, not just capsules. This makes the mapping far less dynamic.

When sending the header that negotiates support for capsules, each side sends an sf-dictionary of sf-integers to indicate the context IDs that they will use for various supported extensions:

`Capsule-Protocol: ecn=1, timestamp=2`

For compression extensions that need dynamic state, they can allocated any context ID values not already allocated in the header via capsules:

```
REGISTER_COMPRESSION_CONTEXT {
	Context = 3,
	Source IP address = foo,
	Destination IP address = bar
}
```

If any context ID ever overlaps, this is treated as an error.

Pros:
- Extensions only ever need one VLI at the start, for both static extensions and dynamic extensions that need capsule negotiation.
- Most context IDs can be learned from headers, reducing the need for dynamic logic.
- The initial VLI can pretty much always be just one byte, since each side can make sure to allocate low values.

Cons:
- Datagram parsing requires some state management (looking at the mapping created by the headers or capsules), even when just using static extensions.

**Comment by DavidSchinazi** [comment]
I like this proposal, it keeps the core CONNECT-UDP document simple while still enabling extension composability for extensions that desire it. In terms of allocation of the VLI, Option 2 sounds like a much better path forward than option 1.

Varints exist to leverage the probabilistic imbalance, and if we send IANA-registered values in varints, we'll encourage folks to fight over low values which could lead to collisions. Also reusing the capsule type here doesn't make sense to me, these aren't capsules, they're datagram format types.

**Comment by tfpauly** [comment]
@afrind Right, you could consider a hybrid with some fixed values and some dynamic ones. However, unless we defined a specific boundary (or a scheme like skipping every other number), I'd be a bit concerned about the two sides not agreeing on which of the values were available for dynamic allocation.

**Comment by bemasc** [comment]
I like this direction.  Some variations:

1. Simpler.  Instead of sf-dictionary[sf-int], how about just sf-list?
```
Capsule-Protocol: ecn, timestamp
```
The indices are the IDs, starting at 1.  (Zero is reserved for the default format.)

2. More compact: Allow parameters on static allocations (sf-params on sf-int):
```
Capsule-Protocol: 1; ecn=1, 2; ecn=2, 3; ecn=3, 4; timestamp
```
This saves one byte of overhead for ECN.

Having both static and dynamic registrations in the same context ID space seems weird to me.  If we have dynamic registrations, then we don't need the header, so it's just additive complexity.

There's also some awkwardness around negotiation.  If negotiation also registers the context IDs, then it can't be used with a dynamic compression format, which can't be registered yet.  That means that when you attempt dynamic registration, you doesn't know if the peer supports this format at all, so we also need a dynamic rejection signal.

It might be cleaner to stick to purely static Type ID allocation, and move the dynamic allocation inside the relevant payload section, e.g.
```
Capsule-Protocol: ecn, timestamp, compress

Capsule REGISTER_COMPRESSION_CONTEXT {
  Compression-Context = 52,
  Source IP address = foo,
  Destination IP address = bar
}

Timestamp+ECN+Compression Datagram {
  Type = 2
  Timestamp = 87814829852
  Type = 1
  ECN = 2
  Type = 3
  Compression-Context = 52
  Compressed-Payload = ...
}
```
This costs ~1 byte, but it avoids the situation of having multiple capsule types that are modifying a shared ID space.

**Comment by kazuho** [comment]
I also like the direction.

IIUC, the approach is to let each side _declare_ the types that it would use and the IDs being used for each type. That declaration is being done using HTTP headers.

It makes sense to declare them in HTTP headers, because HTTP applications are required to process request headers before processing the request payload, even when the payload arrives before the headers (due to reordering). To paraphrase, by using of headers, we can rely on existing mechanism to handle out-of-order delivery of DATAGRAM frames.

@bemasc 
> 1. Simpler. Instead of sf-dictionary[sf-int], how about just sf-list?

+1.

> Having both static and dynamic registrations in the same context ID space seems weird to me. If we have dynamic registrations, then we don't need the header, so it's just additive complexity.

+1.

**Comment by tfpauly** [comment]
@bemasc Yeah the static only approach is essentially what I was trying to get at with option 1. I like how you express it too.

**Comment by afrind** [comment]
> It might be cleaner to stick to purely static Type ID allocation, and move the dynamic allocation inside the relevant payload section

This has always made the most sense to me. 

> Capsule-Protocol: ecn, timestamp, compress

Just to make sure I understand your example, `ecn` and `timestamp` are defined as "further composable" but `compress` is not?  Would most types register both a composable and non-composable code point?

**Comment by tfpauly** [comment]
> Just to make sure I understand your example, ecn and timestamp are defined as "further composable" but compress is not? Would most types register both a composable and non-composable code point?

Yes, I think the compressed payload would not let itself be followed by another extension, since it is replacing the uncompressed default payload. So it can simply be the terminal payload of the datagram.

**Comment by bemasc** [comment]
> Just to make sure I understand your example, `ecn` and `timestamp` are defined as "further composable" but `compress` is not?

Yes.  Tommy's `Next Type` field in the format for `ECN` seems like a good way to think about this.

> Would most types register both a composable and non-composable code point?

No, most types would only have one codepoint, and be intrinsically composable (header-like) or non-composable (body-like).

**Comment by tfpauly** [comment]
To write this up in the format before, I think this is what we're landing on:

### Option 3: Determine values in header

The VLI at the start of the datagram is an ID defined per request stream to map to a single extension type that determines the datagram format, and is allocated by a header in the request. Extensions that need dynamic markers, like compression, define their own interior formats that can include compression contexts.

When sending the header that negotiates support for capsules, the client sends an sf-list, with an sf-token for each extension it intends to use. Each extension is implicitly assigned an integer value, starting at 1, which is later used in the datagram as the VLI. The server includes a list of its supported extensions in its response; while the server may not support some values from the client, it does not change the integers assigned for use in datagrams.

For example, if the client sends this:

`Capsule-Protocol: ecn, timestamp`

ECN is assigned `1`, and timestamp is assigned `2`.

For the (common) case where no extension is supported, the list simply includes one item, which is an sf-boolean instead of an sf-token:

`Capsule-Protocol: ?1`

(Alternatively we could define a different header for the extensions, but I think we should define that in h3-datagram?)

Pros:
- The initial VLI will almost always be just one byte, since it is highly unlikely that the client will list more than 62 extensions in its request
- Clients can start sending datagrams using extensions as soon as they send their request
- No changing of the meaning of the first VLI after processing the request

Cons (minimal, IMO):
- Extensions that use dynamic state, like compression, need to use another marker (like a VLI) for their context. This space overhead is minimal, however, especially given that the first VLI will essentially always be one byte only.
- Datagram parsing requires remembering the values passed in the client request.

**Comment by afrind** [comment]
>  Each extension is implicitly assigned an integer value, starting at 1, which is later used in the datagram as the VLI. The server includes a list of its supported extensions in its response; while the server may not support some values from the client, it does not change the integers assigned for use in datagrams.

Then I'm on option 4, everything else is the same as Option 3, but each extension has a code point allocated by its specification.  I can't see an advantage in Option 3 to having ecn having different code points per request depending on the order specified in a header.  Yes, it will cost another byte when we get to 62 extensions, but does anyone practically think we're going to get there?

**Comment by tfpauly** [comment]
One benefit of not having fixed numbers for the extensions is that we don't need to worry about a numbered registry across different protocols; we just can have a extension name registry.

I think that it's certainly possible to hit more than 62 extensions total over the lifetime of the protocol, whereas its essentially impossible to hit that many for a given request.

Turning the question around: what is the burden of having the values be determined by the request? The quarter stream ID is already dependent on the request, so it seems like you could populate all the information at the same time.

**Comment by bemasc** [comment]
I would spell "no extensions" by omitting the header.

Using fixed values doesn't really simplify anything because we still need
the same header to negotiate support, so I think dynamic values are
sensible (and avoid any concern about trying to get earlier registry
entries).

**Comment by afrind** [comment]
> One benefit of not having fixed numbers for the extensions is that we don't need to worry about a numbered registry across different protocols; we just can have a extension name registry.

We have such registries for HTTP/2 and HTTP/3 frame types, and errors, etc.

> I think that it's certainly possible to hit more than 62 extensions total over the lifetime of the protocol

Possible yes.  Probable no.

> Turning the question around: what is the burden of having the values be determined by the request? The quarter stream ID is already dependent on the request, so it seems like you could populate all the information at the same time.

The burden is in the receiver having to do a lookup to know how to parse the datagram.  We could have done this with QUIC too -- instead of giving each QUIC frame a code point, we could have the transport params negotiate the code points it wants for each frame.  Why didn't we do this?  It's slow and unnecessary.

**Comment by LPardue** [comment]
> I would spell "no extensions" by omitting the header.

We get this for free, which is neat. Per https://www.rfc-editor.org/rfc/rfc8941.html#section-3.1-6

> An empty List is denoted by not serializing the field at all. This implies that fields defined as Lists have a default empty value.

**Comment by tfpauly** [comment]
The reason I left the header was that it was already around for saying "I use capsules at all", but if we use a different header or decide we don't need that original header, then yes an empty/omitted list works.

**Comment by tfpauly** [comment]
> The burden is in the receiver having to do a lookup to know how to parse the datagram. We could have done this with QUIC too -- instead of giving each QUIC frame a code point, we could have the transport params negotiate the code points it wants for each frame. Why didn't we do this? It's slow and unnecessary.

I think QUIC frames is arguably a bit different: QUIC frames can be parsed regardless of any other knowledge, already.  The payload of datagram frames, on the other hand, already requires that you understand the quarter-stream ID based on a request you've received. Since you have to wait to interpret this, this is essentially saying you use the request to interpret the first two octets of the datagram rather than just the first one octet.

**Comment by afrind** [comment]
> Since you have to wait to interpret this, this is essentially saying you use the request to interpret the first two octets of the datagram rather than just the first one octet.

Waiting is ok.  Using another octet to figure out what to do is ok.  Allowing the peer to map the same semantics to  different octets for every request is the unnecessary part.  I don't see the value there.

**Comment by bemasc** [comment]
> The reason I left the header was that it was already around for saying "I use capsules at all", but if we use a different header or decide we don't need that original header, then yes an empty/omitted list works.

OK.  My preference would be for `Capsule-Protocol = sh-boolean` and `Datagram-Formats = sf-list`.

Regarding renumbering the formats: I think this is actually helpful, conceptually, because it makes it clearer that these formats have no meaning outside of their Request/Response context.  If you haven't seen the corresponding header value, there's no guarantee that you can even parse the datagram, and implementations should resist any temptation to try.

**Comment by tfpauly** [comment]
I like `Datagram-Formats = sh-list` as an option.

I also agree with @bemasc about the numbering being determined by the request. If we're already waiting for the request to be able to know the quarter stream ID, I don't think it's a burden to have the format numbering be based on state from that request.

**Comment by tfpauly** [comment]
Here's a very simple reduction to just have a static registry for formats, with no flags: #73

**Comment by tfpauly** [comment]
(To be clear, I'd probably prefer a dynamic setup)

**Comment by DavidSchinazi** [comment]
Thanks Tommy. I've updated #70 so that HTTP headers can now be used to register context IDs. I think that makes it a lot simpler.
