### ISSUE TITLE
Supporting Don't Fragment (or not)

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-udp#74]
An application that tunnels UDP may rely on certain properties or features of the socket that the proxy creates. The draft covers some of these but doesn't seem to mention the UDP fragmentation. TURN has a whole section on this https://www.rfc-editor.org/rfc/rfc8656.html#section-3.7

QUIC, for example, requires that `UDP datagrams MUST NOT be fragmented at the IP layer` and recommends the Don't Fragment (DF) bit MUST be set if possible. 

Since a proxy is agnostic to the application protocol in use (I'm assuming that because we don't mention the [ALPN header](https://datatracker.ietf.org/doc/html/rfc7639) anywhere) perhaps CONNECT-UDP would benefit from a signal the client can send to the proxy to state it's DF preferences.

**Comment by DavidSchinazi** [comment]
This sounds like a worthwhile extension draft? I don't think it's required to have a functional CONNECT-UDP protocol

**Comment by LPardue** [comment]
One argument for doing it here is that one of the common uses of CONNECT-UDP will be to tunnel QUIC, and this is an obvious footgun in consideration of RFC 9000 requirements. 

The opposite way to solve the problem could be to add MUST/SHOULD language about setting DF by default. And then require an extension to signal to disable it. But this is solutionizing a bit.

Really, I want to be able to write a client that can have consistent expectations about the way datagram payload gets sent on UDP. Otherwise when things go wrong I'm left guessing and I might not have the information that the proxy did. I could even live with text in this document that raises this as a consideration but punts on the problem.

**Comment by bemasc** [comment]
Note that this isn't just about setting `DF` in IPv4.  It's also about whether to apply sender fragmentation, in IPv6.

I would be OK with declaring that all fragmentation is off by default, and leave it to extensions to turn it on.

**Comment by LPardue** [comment]
Good point Ben!

**Comment by DavidSchinazi** [comment]
I'd be OK with saying proxies MUST NOT explicitly add fragmentation and SHOULD set the DF bit. We can't say MUST set DF because not all operating systems allow setting the DF bit on UDP sockets.

**Comment by LPardue** [comment]
RFC 9000 says `In IPv4 [IPv4], the Don't Fragment (DF) bit MUST be set if possible, to prevent fragmentation on the path.`, not a fan?

**Comment by DavidSchinazi** [comment]
"MUST ... if possible" is the same as "SHOULD" for me, I don't much care between them.
