### ISSUE TITLE
CONNECT-UDP needs a request target URI

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-connect-udp#8]
Issue created by me on [2020-08-13](https://github.com/DavidSchinazi/masque-drafts/issues/29):

[connect-udp-00 s3](https://tools.ietf.org/html/draft-schinazi-masque-connect-udp-00#section-3) mainly copied most of the CONNECT-UDP design from CONNECT, but than goes against some existing HTTP semantics. In particular, every HTTP method is supposed to use URIs to represent their request target (this was mentioned in [RFC 7231 s2](https://tools.ietf.org/html/rfc7231#section-2) and clarified in [draft-ietf-httpbis-semantics s6.1](https://tools.ietf.org/html/draft-ietf-httpbis-semantics-10#section-6.1)). CONNECT and OPTIONS are noted as existing exceptions, but new methods are not allowed exceptions, to allow intermediaries to proxy unknown methods. CONNECT-UDP only cares about the authority (host and port) portion of the URI, so we can easily encode that as an URI and mandate that the path MUST be "/" and the query MUST be empty. The main open question is what scheme to use. We could either reuse https, or register a new one.

**Comment by DavidSchinazi** [comment]
Comment by @mirjak on 2020-08-14:

draft-ietf-httpbis-semantics notes CONNECT as a special case because it's only used for tunnelling by proxies and usually not even implemented by the origin server. This is the same scenario as we have for any new connect method and I think we should therefore follow the same semantics as already defined for CONNECT.

**Comment by DavidSchinazi** [comment]
Comment by @MikeBishop on 2020-08-14:

`udp://target-host:port`?

**Comment by chris-wood** [comment]
From IETF 109: Strong support in the room to go with:

```
masque://target-host:port
```

**Comment by ekr** [comment]
I'm actually less sure about masque://. It seems naively like this URI would refer to "do masque with this proxy"

**Comment by tfpauly** [comment]
Agreed with @ekr. While `udp://` probably isn't right, `masque://` seems misleading.

**Comment by DavidSchinazi** [comment]
This should be fixed in today's update to the drafts.

**Comment by mirjak** [comment]
I say that you adopted `masque://` in the draft, however,  don't think we reached consensus on this. I recommend to reopen this issue and continue the discussion.

**Comment by ekr** [comment]
I concur with Mirja here.

**Comment by chris-wood** [comment]
Re-opening, as this was not confirmed on the list.

**Comment by DavidSchinazi** [comment]
@chris-wood Do we still need this issue now that we have #23? We definitely need one issue to keep the discussion open but having two makes things confusing.

**Comment by chris-wood** [comment]
Oh, likely not! I didn't realize #23 was also discussing this issue. Let's consolidate discussion over there.
