### ISSUE TITLE
Possibly foreshadow the specific HTTP version exchanges in Section 3

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-udp#97]
Section 3 talks at a high level, which seems ok. But an eager reader might want to skip to the specific requests for their version of choice.

**Comment by DavidSchinazi** [comment]
I tried to add this, but it became awkward because requests and responses are in separate subsections. I think such an eager reader can just use the table of contents to jump ahead and will be fine. If you feel strongly can you send a PR?
